export * from "./MainSection";
export * from "./VideoSection";
export * from "./ThemeSection";
export * from "./ExampleSection";
export * from "./RequirementsSection";
export * from "./AwardsSection";
export * from "./RulesSection";
export * from "./EmailSection";
export * from "./FooterSection";
